name       : perl-datetime-timezone
version    : '2.15'
release    : 2
source     :
    - https://www.cpan.org/authors/id/D/DR/DROLSKY/DateTime-TimeZone-2.15.tar.gz : 06feaca8c5abfac73b262bb94a1b6c428b7098f6b2c1ac896c9785924cd8d428
license    : Artistic-2.0
component  : programming.perl
summary    : Time zone object base class and factory
description: |
    Time zone object base class and factory
runddeps   :
    - perl-datetime
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
