name       : perl-datetime-timezone
version    : '2.19'
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-TimeZone-2.19.tar.gz : b9192efe202d71b4ff7840718807a244bfca3992afd7e7ca78da20849f5ea4f8
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Time zone object base class and factory
description: |
    Time zone object base class and factory
builddeps  :
    - perl-b-hooks-endofscope
    - perl-class-data-inheritable
    - perl-class-singleton
    - perl-datetime
    - perl-devel-stacktrace
    - perl-eval-closure
    - perl-exception-class
    - perl-module-implementation
    - perl-module-runtime
    - perl-mro-compat
    - perl-namespace-autoclean
    - perl-namespace-clean
    - perl-package-stash
    - perl-params-validationcompiler
    - perl-role-tiny
    - perl-specio-exporter
    - perl-sub-exporter-progressive
    - perl-sub-identify
    - perl-test-fatal
    - perl-test-requires
    - perl-test-simple
    - perl-try-tiny
runddeps   :
    - perl-datetime
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
