name       : perl-datetime-timezone
version    : 2.11
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/DateTime-TimeZone-2.11.tar.gz : a7c0b2581d2bf6d5cc535364099a67678a9f6ee608e5042dff9ef9c4c577ea6b
license    : Artistic-2.0
component  : programming.perl
summary    : Time zone object base class and factory
description: |
    Time zone object base class and factory
runddeps   :
    - perl-datetime
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
