name       : perl-datetime-timezone
version    : '2.17'
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-TimeZone-2.17.tar.gz : 1d0a0adc8a14adc8033b5e5391f1b2b87fe48151d95c019601a390020f9770b2
license    : Artistic-2.0
component  : programming.perl
summary    : Time zone object base class and factory
description: |
    Time zone object base class and factory
builddeps  :
    - perl-b-hooks-endofscope
    - perl-class-data-inheritable
    - perl-class-singleton
    - perl-datetime
    - perl-devel-stacktrace
    - perl-eval-closure
    - perl-exception-class
    - perl-module-implementation
    - perl-module-runtime
    - perl-mro-compat
    - perl-namespace-autoclean
    - perl-namespace-clean
    - perl-package-stash
    - perl-params-validationcompiler
    - perl-role-tiny
    - perl-specio-exporter
    - perl-sub-exporter-progressive
    - perl-sub-identify
    - perl-test-fatal
    - perl-test-requires
    - perl-test-simple
    - perl-try-tiny
runddeps   :
    - perl-datetime
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
