name       : perl-datetime-timezone
version    : '2.49'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-TimeZone-2.49.tar.gz : 01717ec4180b46c321e62e360200f32a99181686bff6eac7a93bf2507a0a1552
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Time zone object base class and factory
description: |
    Time zone object base class and factory
builddeps  :
    - perl-b-hooks-endofscope
    - perl-class-data-inheritable
    - perl-class-singleton
    - perl-datetime
    - perl-devel-stacktrace
    - perl-eval-closure
    - perl-exception-class
    - perl-module-implementation
    - perl-module-runtime
    - perl-mro-compat
    - perl-namespace-autoclean
    - perl-namespace-clean
    - perl-package-stash
    - perl-params-validationcompiler
    - perl-role-tiny
    - perl-specio-exporter
    - perl-sub-exporter-progressive
    - perl-sub-identify
    - perl-test-fatal
    - perl-test-requires
    - perl-test-simple
    - perl-try-tiny
rundeps    :
    - perl-class-singleton
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
