name       : perl-datetime-timezone
version    : '2.54'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-TimeZone-2.54.tar.gz : 1a3e8a7abf91c6beebf644b6c12478414ccf1bb51501ed11f08c02bb21667588
homepage   : https://metacpan.org/pod/DateTime::TimeZone
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : DateTime::TimeZone - Time zone object base class and factory
description: |
    This class is the base class for all time zone objects. A time zone is represented internally as a set of observances, each of which describes the offset from GMT for a given time period.
builddeps  :
    - perl-b-hooks-endofscope
    - perl-class-data-inheritable
    - perl-class-singleton
    - perl-datetime
    - perl-devel-stacktrace
    - perl-eval-closure
    - perl-exception-class
    - perl-module-implementation
    - perl-module-runtime
    - perl-mro-compat
    - perl-namespace-autoclean
    - perl-namespace-clean
    - perl-package-stash
    - perl-params-validationcompiler
    - perl-role-tiny
    - perl-specio-exporter
    - perl-sub-exporter-progressive
    - perl-sub-identify
    - perl-test-fatal
    - perl-test-requires
    - perl-test-simple
    - perl-try-tiny
rundeps    :
    - perl-class-singleton
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
